//!! WARNING => keep that list sync with the list used in tailwind.config.js !!
const themes = [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    // "retro",
    // "cyberpunk",
    // "valentine",
    "halloween",
    "garden",
    "forest",
    // "aqua",
    // "lofi",
    // "pastel",
    "fantasy",
    // "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    // "lemonade",
    "night",
    // "coffee",
    // "winter",
]

export default themes;