const themes = [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    // "retro",
    // "cyberpunk",
    // "valentine",
    "halloween",
    "garden",
    "forest",
    // "aqua",
    // "lofi",
    // "pastel",
    "fantasy",
    // "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    // "lemonade",
    "night",
    // "coffee",
    // "winter",
];

const themesOrg = {
    light: [
        "light",
        "cupcake",
        "bumblebee",
        "emerald",
        "corporate",
        // "retro",
        // "cyberpunk",
        "cmyk",
        // "valentine",
        "garden",
        // "lofi",
        // "pastel",
        "fantasy",
        // "wireframe",
        "autumn",
        "acid",
        // "lemonade",
        // "winter",
    ],
    dark: [
        "dark",
        // "aqua",
        "synthwave",
        "halloween",
        "forest",
        "black",
        // "luxury",
        "business",
        "night",
        "dracula",
        // "coffee",
    ],
};

export default themesOrg;
